image: microsoft/dotnet:2.1-sdk

stages:
  - test
  - code_analysis

test:
  stage: test
  variables:
    test_path: "teste-api/"
  script:
    - "cd $test_path"
    - "dotnet build"
    - "dotnet test"
  only:
      - develop

sonar:
  stage: code_analysis
  variables: 
    SONAR_SCANNER_OPTS: "-Xmx1024m"
  script: 
    - export PATH="$PATH:/root/.dotnet/tools"
    - export SONAR_SCANNER_OPTS
    - apt-get update
    - apt-get install openjdk-8-jre -y
    
    - dotnet tool install --global dotnet-sonarscanner --version 4.4.2
    - dotnet tool install --global coverlet.console --version 1.4.1
    
    - |
      dotnet test ./teste-api --configuration Debug --output ../../output-tests \
      /p:CollectCoverage=true \
      /p:CoverletOutputFormat=opencover \
      /p:CoverletOutput='coverage.opencover.xml'


    - dotnet sonarscanner begin /k:"$SONAR_PROJECT_KEY" /d:sonar.host.url="$SONAR_URL" /d:sonar.login="$SONAR_TOKEN" /d:sonar.analysis.mode=publish
    - dotnet build
    - dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN"
  only:
    - develop